---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-cluster.componentName" (list . "admission-configuration") }}
  labels: {{ include "openstack-cluster.componentLabels" (list . "admission-configuration") | nindent 4 }}
stringData:
  admission-configuration.yaml: |
    apiVersion: apiserver.config.k8s.io/v1
    kind: AdmissionConfiguration
    {{- if .Values.apiServer.admissionConfiguration }}
    plugins:
      {{- range $name, $configuration := .Values.apiServer.admissionConfiguration }}
      - name: {{ $name }}
        configuration: {{ toYaml $configuration | nindent 10 }}
      {{- end }}
    {{- else }}
    plugins: []
    {{- end }}
