docker.io:
  images:
    grafana/grafana:
    - 13.2.1-distroless
ghcr.io:
  images:
    jkroepke/kube-webhook-certgen:
    - 1.8.8
quay.io:
  images:
    kiwigrid/k8s-sidecar:
    - 2.11.2
    prometheus-operator/prometheus-operator:
    - v0.93.1
    prometheus/alertmanager:
    - v0.34.0
    prometheus/node-exporter:
    - v1.12.1-distroless
    prometheus/prometheus:
    - v3.14.0-distroless
registry.k8s.io:
  images:
    kube-state-metrics/kube-state-metrics:
    - v2.20.0
