#!/usr/bin/env python3

import argparse
import json
import os

import requests


parser = argparse.ArgumentParser(
    description = "Updates a dependency key to the latest release in a GitHub repository."
)
parser.add_argument(
    "--dependencies-file",
    default = "./dependencies.json",
    help = "The path of the file containing the dependencies."
)
parser.add_argument("repo", help = "The GitHub repo to get releases from, e.g. helm/helm.")
parser.add_argument("key", help = "The key to update with the new version.")
args = parser.parse_args()


with open(args.dependencies_file) as fh:
    data = json.load(fh)

# Get the latest version from the GitHub API
api_url = f"https://api.github.com/repos/{args.repo}/releases/latest"
response = requests.get(api_url)
response.raise_for_status()
next_version = data[args.key] = response.json()["tag_name"]

with open(args.dependencies_file, "w") as fh:
    json.dump(data, fh, indent = 4)

# Output the next version so it can be consumed by later steps
output_path = os.environ.get("GITHUB_OUTPUT", "/dev/stdout")
with open(output_path, "a") as fh:
    print(f"next-version={next_version}", file = fh)
