apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-addons.componentName" (list . "kyverno") }}-restricted-readonly
  labels:
    {{- include "cluster-addons.componentLabels" (list . "kyverno") | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - "pods"
    - "services"
    - "configmaps"
    - "events"
    - "replicationcontrollers"
    - "limitranges"
    - "resourcequotas"
    - "endpoints"
    - "nodes"
    - "persistentvolumeclaims"
    - "persistentvolumes"
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - "deployments"
    - "daemonsets"
    - "replicasets"
    - "statefulsets"
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - "jobs"
    - "cronjobs"
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
    - "networkpolicies"
    - "ingresses"
  verbs: ["get", "list", "watch"]