{{- range $namespace := ( include "cluster-addons.systemNamespaces" . | splitList " " ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster-addons.componentName" (list . "kyverno") $ }}-restricted
  namespace: {{ $namespace }}
  labels:
    {{- include "cluster-addons.componentLabels" (list $ "kyverno") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-addons.componentName" (list . "kyverno") $ }}-config
  namespace: {{ $.Values.kyverno.release.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "cluster-addons.componentName" (list . "kyverno") $ }}-restricted-readonly
  apiGroup: rbac.authorization.k8s.io
{{- end }}