{{- if .Values.kyverno.enabled }}
# Create a single Manifests resource
apiVersion: addons.stackhpc.com/v1alpha1
kind: Manifests
metadata:
  name: {{ include "cluster-addons.componentName" (list . "kyverno") }}-role-bindings
  labels: {{ include "cluster-addons.componentLabels" (list . "kyverno") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  targetNamespace: {{ .Values.kyverno.release.namespace }}
  releaseName: kyverno
  manifestSources:
      # Read-only role for each system namespace
      {{- range $namespace := ( include "cluster-addons.systemNamespaces" . | splitList " " ) }}
      - template: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-restricted
            namespace: {{ $namespace }}
            labels:
              {{- include "cluster-addons.componentLabels" (list $ "kyverno") | nindent 12 }}
          subjects:
          - kind: ServiceAccount
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-config
            namespace: {{ $.Values.kyverno.release.namespace }}
          roleRef:
            kind: ClusterRole
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-restricted-readonly
            apiGroup: rbac.authorization.k8s.io
      {{- end }}
      {{- if .Values.monitoring.enabled }}
      # Read-only role for each monitoring namespace
      - template: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-restricted
            namespace: monitoring-system
            labels:
              {{- include "cluster-addons.componentLabels" (list $ "kyverno") | nindent 12 }}
          subjects:
          - kind: ServiceAccount
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-config
            namespace: {{ $.Values.kyverno.release.namespace }}
          roleRef:
            kind: ClusterRole
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-restricted-readonly
            apiGroup: rbac.authorization.k8s.io
      {{- end }}
      {{- if .Values.kubernetesDashboard.enabled }}
      # Read-only role for each monitoring namespace
      - template: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-restricted
            namespace: kubernetes-dashboard
            labels:
              {{- include "cluster-addons.componentLabels" (list $ "kyverno") | nindent 12 }}
          subjects:
          - kind: ServiceAccount
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-config
            namespace: {{ $.Values.kyverno.release.namespace }}
          roleRef:
            kind: ClusterRole
            name: {{ include "cluster-addons.componentName" (list $ "kyverno") }}-restricted-readonly
            apiGroup: rbac.authorization.k8s.io
      {{- end }}
{{- end }}