{{- if .Values.kyverno.enabled }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: Manifests
metadata:
  name: {{ include "cluster-addons.componentName" (list . "kyverno") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "kyverno") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  targetNamespace: {{ .Values.kyverno.release.namespace }}
  releaseName: kyverno
  manifestSources:
    # Read-only role for system namespaces
    - template: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: {{ include "cluster-addons.componentName" (list . "kyverno") }}-config
          labels:
            {{- include "cluster-addons.componentLabels" (list . "kyverno") | nindent 4 }}
{{- end }}