#!/bin/sh

#####
# Simple script that selects the correct kubectl version for the target API server
# 
# This is done by making a pre-flight request with the latest kubectl version to get
# the API server version in the hope that it works despite any version skew, being
# the simplest possible API request... :fingerscrossed:
#####

KUBECONFIG_ARG=
KUBECTL_ARGS=

while :; do
    case $1 in
        --kubeconfig)
            KUBECONFIG_ARG="$1 $2"
            shift
            ;;
        --kubeconfig=?*)
            KUBECONFIG_ARG="$1"
            ;;
        ?*)
            KUBECTL_ARGS="$KUBECTL_ARGS $1"
            ;;
        *)
            break
    esac
    shift
done

set -exo pipefail

server_version="$(kubectl-$KUBECTL_VN_LATEST $KUBECONFIG_ARG version -o json | jq -r '"v" + .serverVersion.major + "." + .serverVersion.minor')"
exec kubectl-$server_version $KUBECONFIG_ARG $KUBECTL_ARGS
