#!/bin/sh

set -eo pipefail

#####
# Simple script that selects the correct kubectl version for the target API server
# 
# This is done by making a pre-flight request with the latest kubectl version to get
# the API server version in the hope that it works despite any version skew, being
# the simplest possible API request... :fingerscrossed:
#####

server_version="$(kubectl-$KUBECTL_VN_LATEST version -o json 2>/dev/null | jq -r '"v" + .serverVersion.major + "." + .serverVersion.minor')"
exec kubectl-$server_version "$@"
