{
 "title": "AMD Instinct (Per Node View)",
 "description": "Dashboard to visualize AMD GPU metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "hostname", "label": "Node", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "GPU Mem Utilization",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_used_vram{hostname=\"$hostname\"}",
     "legendFormat": "{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_gfx_activity{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_used_vram{hostname=\"$hostname\"} / gpu_total_vram{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Health",
   "type": "stat",
   "description": "Health of the GPU (0 = Unhealthy | 1 = Healthy)",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_health{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "description": "Graphics engine usage in Percentage (0-100)",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_gfx_activity{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "PCIe Bandwidth",
   "type": "timeseries",
   "description": "Current PCIe bandwidth in Mb/s",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "pcie_bandwidth{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage (W)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_package_power{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Temperature (Celsius)",
   "type": "timeseries",
   "description": "Current junction/hotspot temperature in Celsius",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_junction_temperature{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Mem Utilization (GB)",
   "type": "bargauge",
   "description": "Used VRAM memory of the GPU (in MB)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_used_vram{hostname=\"$hostname\"}",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Average GPU Utilization (All GPUs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(gpu_gfx_activity{hostname=\"$hostname\"}[10m]))",
     "legendFormat": "Average GPU Utilization"
    }
   ]
  },
  {
   "title": "Avg GPU & Mem Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(gpu_gfx_activity{hostname=\"$hostname\"})",
     "legendFormat": "Avg. GPU Utilization"
    },
    {
     "expr": "avg((amd_gpu_used_vram) / (amd_gpu_total_vram)) * 100",
     "legendFormat": "Avg. Memory Utilization"
    }
   ]
  },
  {
   "title": "GPU Utilization Avg/Max/Min (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(gpu_gfx_activity{hostname=\"$hostname\"})",
     "legendFormat": "Avg. GPU Utilization (%)"
    },
    {
     "expr": "min(gpu_gfx_activity{hostname=\"$hostname\"})",
     "legendFormat": "Min. GPU Utilization (%)"
    },
    {
     "expr": "max(gpu_gfx_activity{hostname=\"$hostname\"})",
     "legendFormat": "Max. GPU Utilization (%)"
    }
   ]
  }
 ]
}