{
 "title": "Blackbox Exporter (HTTP prober)",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{target=~\"$target\"}"
    },
    {
     "expr": "probe_http_ssl{target=~\"$target\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{target=~\"$target\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{target=~\"$target\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{target=~\"$target\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{target=~\"$target\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{target=~\"$target\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(probe_http_status_code{target=~\"$target\"}) by(target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_duration_seconds{target=~\"$target\"}) by(target)",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}