{
 "title": "Loki / Metrics",
 "description": "Loki and Promtail metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Loki's stored chunk entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(loki_ingester_chunk_entries_count[5m])"
    }
   ]
  },
  {
   "title": "Average batch appends sent to ingesters (Loki)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate (loki_distributor_ingester_appends_total[1m])"
    }
   ]
  },
  {
   "title": "Number of bytes total by promtail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(promtail_file_bytes_total{pod=~\".*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of bytes encoded and ready to send by Promtail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (promtail_encoded_bytes_total{pod=~'.*'}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}