{{- range $nodeGroupOverrides := .Values.nodeGroups }}
{{- $nodeGroup := deepCopy $.Values.nodeGroupDefaults | mustMerge $nodeGroupOverrides }}
{{- if $nodeGroup.healthCheck.enabled }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "openstack-cluster.componentName" (list $ $nodeGroup.name) }}
  labels:
    {{- include "openstack-cluster.componentLabels" (list $ "worker") | nindent 4 }}
    {{ $.Values.projectPrefix }}/node-group: {{ $nodeGroup.name }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "openstack-cluster.clusterName" $ }}
  selector:
    matchLabels:
      {{- include "openstack-cluster.componentSelectorLabels" (list $ "worker") | nindent 6 }}
      {{ $.Values.projectPrefix }}/node-group: {{ $nodeGroup.name }}
  {{- toYaml $nodeGroup.healthCheck.spec | nindent 2 }}
{{- end }}
{{- end }}
