apiVersion: v2
name: openstack-cluster
description: Helm chart for deploying a cluster on an OpenStack cloud using Cluster API.
type: application
version: 0.1.0
appVersion: main
home: https://github.com/azimuth-cloud/capi-helm-charts
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/changes: |
    - Moved to Quay hosting
  artifacthub.io/license: Apache-2.0

dependencies:
  - name: cluster-addons
    version: ">=0-0"
    repository: file://../cluster-addons
    alias: addons
    condition: addons.enabled
