{{- if or .Values.csiCephfs.enabled .Values.openstack.csiManila.cephfs.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cephfs") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "csi-cephfs") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    tolerations:
      - effect: NoSchedule
    
  overrides: |
    {{- toYaml .Values.csiCephfs.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "csi-cephfs") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "csi-cephfs") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.csiCephfs.chart | nindent 4 }}
  targetNamespace: {{ .Values.csiCephfs.release.namespace }}
  releaseName: csi-manila
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "csi-cephfs") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "csi-cephfs") }}-config
        key: overrides
{{- end }}