{{- if .Values.mellanoxNetworkOperator.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "mellanox-network-operator") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "mellanox-network-operator") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    # Use the shared NFD
    nfd:
      enabled: false
    # Deploy the default NICClusterPolicy
    deployCR: true
    # Deploy the OFED driver onto nodes with a suitable NIC
    ofedDriver:
      deploy: true
      # OFED takes ages to deploy on low-resource nodes
      # The startup probe has a fixed failure threshold of 60
      # So in order to give the drivers up to one hour to install, we use a period
      # of 60 seconds for the startup probe
      startupProbe:
        initialDelaySeconds: 60
        periodSeconds: 60
    # Deploy the RDMA shared device plugin to allow pods to access the RDMA device
    rdmaSharedDevicePlugin:
      deploy: true
    # Disable all other features for now
    ibKubernetes:
      deploy: false
    nvPeerDriver:
      deploy: false
    sriovNetworkOperator:
      enabled: false
    sriovDevicePlugin:
      deploy: false
    secondaryNetwork:
      deploy: false
  overrides: |
    {{- toYaml .Values.mellanoxNetworkOperator.release.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "mellanox-network-operator") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "mellanox-network-operator") | nindent 4 }}
  annotations:
    # Tell Argo to ignore the non-controller owner references for this object
    argocd.argoproj.io/sync-options: "ControllerReferencesOnly=true"
    # When using the Argo addon provider, we want to use regular apply for the generated app
    # This is because some of the resources fail to validate when using server-side apply
    # See https://github.com/Mellanox/network-operator/issues/452
    #
    # We use the annotation rather than the spec so that the resource is compatible with
    # both the legacy and Argo addon providers
    addons.stackhpc.com/sync-options: |
      { "serverSideApply": false }
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.mellanoxNetworkOperator.chart | nindent 4 }}
  targetNamespace: {{ .Values.mellanoxNetworkOperator.release.namespace }}
  releaseName: mellanox-network-operator
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "mellanox-network-operator") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "mellanox-network-operator") }}-config
        key: overrides
{{- end }}
