{{- if .Values.nvidiaGPUOperator.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-addons.componentName" (list . "nvidia-gpu-operator") }}-config
  labels:
    {{- include "cluster-addons.componentLabels" (list . "nvidia-gpu-operator") | nindent 4 }}
    addons.stackhpc.com/watch: ""
stringData:
  defaults: |
    # Use the shared NFD
    nfd:
      enabled: false
    # Export operator and node metrics in a Prometheus format.
    # The component provides information on the status of the
    # operator (e.g. reconciliation status, number of GPU enabled nodes).
    nodeStatusExporter:
      enabled: true
    toolkit:
      env:
        # Allowing the toolkit to edit /etc/containerd/config.toml (the default)
        # breaks nvidia pod deployment on clusters with Harbor cache enabled.
        # Instead make a new config file specifically for nvidia runtime config,
        # which is parsed as an "include" in the main containerd config file.
        #
        # https://github.com/NVIDIA/gpu-operator/issues/301
        - name: "CONTAINERD_CONFIG"
          value: "/etc/containerd/conf.d/nvidia.toml"
        # Default is "command,file", which tries to retrieve config by running
        # `containerd config dump`, which outputs config migrated to the containerd client
        # used by NVIDIA Container Toolkit and only uses the version from config.toml if
        # this fails. This means the config drop-in generated from this can be incompatible
        # with the containerd version in the image and crash containerd. Workaround
        # to only use config.toml as config source. https://github.com/NVIDIA/aicr/issues/1688
        - name: "RUNTIME_CONFIG_SOURCE"
          value: "file"
  overrides: |
    {{- toYaml .Values.nvidiaGPUOperator.release.values | nindent 4 }}
---
apiVersion: addons.stackhpc.com/v1alpha1
kind: HelmRelease
metadata:
  name: {{ include "cluster-addons.componentName" (list . "nvidia-gpu-operator") }}
  labels: {{ include "cluster-addons.componentLabels" (list . "nvidia-gpu-operator") | nindent 4 }}
spec:
  clusterName: {{ include "cluster-addons.clusterName" . }}
  bootstrap: true
  chart: {{ toYaml .Values.nvidiaGPUOperator.chart | nindent 4 }}
  targetNamespace: {{ .Values.nvidiaGPUOperator.release.namespace }}
  releaseName: nvidia-gpu-operator
  valuesSources:
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "nvidia-gpu-operator") }}-config
        key: defaults
    - secret:
        name: {{ include "cluster-addons.componentName" (list . "nvidia-gpu-operator") }}-config
        key: overrides
{{- end }}
