---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.clusterAnnotations | nindent 4 }}
spec:
  clusterNetwork: {{ .Values.kubeNetwork | toYaml | nindent 4 }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "openstack-cluster.componentName" (list . "control-plane") }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: {{ include "openstack-cluster.clusterName" . }}
    namespace: {{ .Release.Namespace }}
