---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: {{ include "openstack-cluster.clusterName" . }}
  labels: {{ include "openstack-cluster.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.clusterAnnotations | nindent 4 }}
spec:
  clusterNetwork: {{ .Values.kubeNetwork | toYaml | nindent 4 }}
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: {{ include "openstack-cluster.componentName" (list . "control-plane") }}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: OpenStackCluster
    name: {{ include "openstack-cluster.clusterName" . }}
