{{- if .Values.etcd.encryption.enabled }}
---
apiVersion: v1
kind: ServiceAccount
annotations:
  helm.sh/hook: pre-install
  helm.sh/hook-weight: "0"
  helm.sh/resource-policy: keep
metadata:
  name: {{ .Release.Name }}-secret-gen-hook
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-secret-gen-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
    helm.sh/resource-policy: keep
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - delete
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-secret-gen-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
    helm.sh/resource-policy: keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-secret-gen-hook
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-secret-gen-hook
  namespace: {{ .Release.Namespace }}
---
# Create secrets dynamically retrievable by helm on cluster creation
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-secret-create
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: secret-creater
        image: gcr.io/google_containers/hyperkube:v1.18.0
        command:
        - kubectl
        - create
        - secret
        - generic
        - {{ .Release.Name }}-etcd-key
        - --from-literal=key={{ randAlphaNum 32 }}
        - -n
        - {{ .Release.Namespace }}
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-secret-gen-hook
---
# Delete secret on cluster deletion
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-secret-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "4"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: secret-cleaner
        image: gcr.io/google_containers/hyperkube:v1.18.0
        command:
        - kubectl
        - delete
        - secret
        - {{ .Release.Name }}-etcd-key
        - -n
        - {{ .Release.Namespace }}
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-secret-gen-hook
{{- end }}
