clouds:
  leafcloud:
    verify: false

clusterNetworking:
  externalNetworkId: ee54f79e-d33a-4866-8df0-4a4576d70243
  internalNetwork:
    networkFilter:
      id: 96b9024a-0591-4db6-b9e6-e19b85192dbf

controlPlane:
  machineFlavor: ec1.medium
  machineCount: 1

nodeGroups:
  - name: md-0
    machineFlavor: ec1.medium
    machineCount: 2

addons:
  openstack:
    csiCinder:
      defaultStorageClass:
        availabilityZone: europe-nl-ams1
        volumeType: unencrypted
