name: Ensure CAPI images
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: The Git ref under test.
        required: true
    outputs:
      kube-1-33-image:
        value: ${{ jobs.produce_outputs.outputs.kube-1-33-image }}
      kube-1-33-version:
        value: ${{ jobs.produce_outputs.outputs.kube-1-33-version }}
      kube-1-34-image:
        value: ${{ jobs.produce_outputs.outputs.kube-1-34-image }}
      kube-1-34-version:
        value: ${{ jobs.produce_outputs.outputs.kube-1-34-version }}
      kube-1-35-image:
        value: ${{ jobs.produce_outputs.outputs.kube-1-35-image }}
      kube-1-35-version:
        value: ${{ jobs.produce_outputs.outputs.kube-1-35-version }}

jobs:
  image_manifest:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.images.outputs.manifest }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Fetch image details
        id: images
        run: |
          VN="$(jq -r '.["azimuth-images"]' ./dependencies.json)"
          MANIFEST="$(curl -fsSL "https://github.com/azimuth-cloud/azimuth-images/releases/download/${VN}/manifest.json")"
          echo "manifest=$(jq -c . <<< "$MANIFEST")" >> $GITHUB_OUTPUT

  ensure_image:
    runs-on: ubuntu-latest
    needs: [image_manifest]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: kube-1-33
            image: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-33-jammy }}
            skip: ${{ github.event.pull_request.draft }}
          - name: kube-1-34
            image: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-34-jammy }}
            skip: false
          - name: kube-1-35
            image: ${{ fromJSON(needs.image_manifest.outputs.manifest).kubernetes-1-35-jammy }}
            skip: false
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}
        if: ${{ !matrix.skip }}

      - name: Write cloud credential
        run: echo "$OS_CLOUDS" > clouds.yml
        shell: bash
        env:
          OS_CLOUDS: ${{ secrets.OS_CLOUDS }}
        if: ${{ !matrix.skip }}

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'
          check-latest: true
        if: ${{ !matrix.skip }}

      - name: Install OpenStack CLI
        run: pip install python-openstackclient
        if: ${{ !matrix.skip }}

      - name: Ensure Kubernetes image
        id: ensure-image
        uses: ./.github/actions/ensure-image
        with:
          os-cloud: ${{ vars.TARGET_CLOUD }}
          image-name: ${{ matrix.image.name }}
          image-url: ${{ matrix.image.url }}
        if: ${{ !matrix.skip }}

      - name: Write matrix outputs
        run: |
          mkdir -p matrix-outputs
          jq -n \
            --arg key "$MATRIX_NAME" \
            --arg image_id "$IMAGE_ID" \
            --arg kube_version "$KUBE_VERSION" \
            '{
              "image-id": {($key): $image_id},
              "kube-version": {($key): $kube_version}
            }' > "matrix-outputs/${MATRIX_NAME}.json"
        env:
          IMAGE_ID: ${{ steps.ensure-image.outputs.image-id }}
          KUBE_VERSION: ${{ matrix.image.kubernetes_version }}
          MATRIX_NAME: ${{ matrix.name }}
        if: ${{ !matrix.skip }}

      - name: Upload matrix outputs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: matrix-outputs-${{ matrix.name }}
          path: matrix-outputs/${{ matrix.name }}.json
        if: ${{ !matrix.skip }}

  produce_outputs:
    runs-on: ubuntu-latest
    needs: [ensure_image]
    outputs:
      kube-1-33-image: ${{ fromJSON(steps.matrix-outputs.outputs.result).image-id.kube-1-33 }}
      kube-1-33-version: ${{ fromJSON(steps.matrix-outputs.outputs.result).kube-version.kube-1-33 }}
      kube-1-34-image: ${{ fromJSON(steps.matrix-outputs.outputs.result).image-id.kube-1-34 }}
      kube-1-34-version: ${{ fromJSON(steps.matrix-outputs.outputs.result).kube-version.kube-1-34 }}
      kube-1-35-image: ${{ fromJSON(steps.matrix-outputs.outputs.result).image-id.kube-1-35 }}
      kube-1-35-version: ${{ fromJSON(steps.matrix-outputs.outputs.result).kube-version.kube-1-35 }}
    steps:
      - name: Download matrix outputs
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: matrix-outputs-*
          merge-multiple: true
          path: matrix-outputs

      - name: Combine matrix outputs
        id: matrix-outputs
        run: |
          echo "result=$(jq -sc 'reduce .[] as $x ({}; . * $x)' matrix-outputs/*.json)" >> $GITHUB_OUTPUT
