name: Publish dependencies on release
on:
  push:
    tags:
      - "**"

jobs:
  mirror_container_images:
    uses: ./.github/workflows/sync-images.yaml
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  publish_charts:
    uses: ./.github/workflows/publish-charts.yaml
    secrets: inherit
    with:
      ref: ${{ github.sha }}

  publish_dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Publish manifest to release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          files: dependencies.json
