name: Update addons
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

jobs:
  test_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: helm-template
        uses: stackhpc/github-actions/helm-template@master
        with:
          repository: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          version: 55.5.1
          values: |
            alertmanager:
              alertmanagerSpec:
                retention: 168h
                storage:
                  volumeClaimTemplate:
                    spec:
                      accessModes: ["ReadWriteOnce"]
                      resources:
                        requests:
                          storage: 10Gi
            prometheus:
              prometheusSpec:
                retention: 90d
                storageSpec:
                  volumeClaimTemplate:
                    spec:
                      accessModes: ["ReadWriteOnce"]
                      resources:
                        requests:
                          storage: 10Gi

      - uses: stackhpc/github-actions/k8s-extract-images@master
        id: extract-images
        with:
          manifests-file: ${{ steps.helm-template.outputs.manifests-file }}

      - name: Write Skopeo manifest
        id: skopeo-manifest
        uses: stackhpc/github-actions/skopeo-manifest@feature/skopeo-manifest
        with:
          manifest-file: ./skopeo-manifest.yaml
          images: ${{ steps.extract-images.outputs.images }}

      - run: cat $MANIFEST_FILE
        env:
          MANIFEST_FILE: ${{ steps.skopeo-manifest.outputs.manifest-file }}
